#!/usr/bin/env fish

abbr -g j 'cd'
abbr -g jR 'cd /'
abbr -g ju 'cd ..'
abbr -g jh 'cd ~'
abbr -g jB 'cd - &> /dev/null'
abbr -g jc 'cd ~/.config/'
abbr -g jb 'cd ~/bin'
abbr -g jd 'cd ~/downloads'
abbr -g jn 'cd ~/notes'
abbr -g jng 'cd ~/notes/ge'
abbr -g jw 'cd ~/wikis'
abbr -g jtd 'cd ~/todos'
abbr -g jr 'cd ~/repos'
abbr -g jt 'cd ~/temp'
abbr -g jU 'cd /run/media/sandy/USB'
abbr -g jp 'cd ~/repos/portal'
abbr -g jg 'cd ~/repos/graphiti'
abbr -g jl 'cd ~/repos/lumos'
abbr -g jf 'cd ~/.config/fish/'
abbr -g jfa 'cd ~/.config/fish/abbreviations'
abbr -g jff 'cd ~/.config/fish/functions'
