#!/usr/bin/env fish

abbr -g gR 'cd /'
abbr -g gu 'cd ..'
abbr -g gh 'cd ~'
abbr -g gB 'cd - &> /dev/null'
abbr -g gc 'cd ~/.config/'
abbr -g gb 'cd ~/bin'
abbr -g gd 'cd ~/downloads'
abbr -g gn 'cd ~/notes'
abbr -g gr 'cd ~/repos'
abbr -g gt 'cd ~/temp'
abbr -g gT 'cd ~/todo'
abbr -g gU 'cd /run/media/sandy/USB'
abbr -g gp 'cd ~/repos/portal'
abbr -g gg 'cd ~/repos/graphiti'
abbr -g gl 'cd ~/repos/lumos'
abbr -g gf 'cd ~/.config/fish/'
abbr -g gfa 'cd ~/.config/fish/abbreviations'
abbr -g gff 'cd ~/.config/fish/functions'
