#!/usr/bin/env fish

abbr -g j 'cd'
abbr -g jR 'cd /'
abbr -g ju 'cd ..'
abbr -g jh 'cd ~'
abbr -g jB 'cd - &> /dev/null'
abbr -g jc 'cd ~/.config/'
abbr -g jb 'cd ~/bin'
abbr -g jd 'cd ~/downloads'
abbr -g jn 'cd ~/repos/personal/notes'
abbr -g jw 'cd ~/wikis'
abbr -g jtd 'cd ~/repos/personal/notes/todos'
abbr -g jr 'cd ~/repos'
abbr -g jrg 'cd ~/repos/ge'
abbr -g jrp 'cd ~/repos/personal'
abbr -g jt 'cd ~/temp'
abbr -g jU 'cd /run/media/sandy/USB'
abbr -g jp 'cd ~/repos/ge/portal'
abbr -g jg 'cd ~/repos/ge/graphiti'
abbr -g jk 'cd ~/repos/personal/kamikaze'
abbr -g jl 'cd ~/repos/ge/lumos'
abbr -g jf 'cd ~/.config/fish/'
abbr -g jfa 'cd ~/.config/fish/abbreviations'
abbr -g jff 'cd ~/.config/fish/functions'
